// src/lib/fiscal-data/validator/create-pr.ts

import { exec } from "child_process"
import { promisify } from "util"
import { writeFile, readFile } from "fs/promises"
import path from "path"
import type { ValidationResult } from "../types"

const execAsync = promisify(exec)

const GITHUB_TOKEN = process.env.GITHUB_TOKEN
const GITHUB_REPO = process.env.GITHUB_REPO || "your-org/FiskAI"
const GITHUB_API = "https://api.github.com"

/**
 * Generate PR body with change details
 */
function generatePRBody(changes: ValidationResult[]): string {
  const now = new Date().toLocaleDateString("hr-HR", {
    day: "numeric",
    month: "long",
    year: "numeric",
  })

  const changesTable = changes
    .map((c) => {
      const confidence = Math.round(c.confidence * 100)
      return `| \`${c.dataPoint}\` | ${c.currentValue} | ${c.foundValue} | ${confidence}% | [Izvor](${c.sourceUrl}) |`
    })
    .join("\n")

  const sourcesList = [...new Set(changes.map((c) => c.sourceUrl))]
    .map((url) => `- ${url}`)
    .join("\n")

  const extractedDetails = changes
    .map(
      (c) => `
**${c.dataPoint}:**
> ${c.extractedText || "Nije pronađen kontekst"}
>
> Pouzdanost: ${Math.round(c.confidence * 100)}%
`
    )
    .join("\n")

  return `## 🔄 Ažuriranje fiskalnih podataka - ${now}

### Otkrivene promjene

| Vrijednost | Trenutno | Novo | Pouzdanost | Izvor |
|------------|----------|------|------------|-------|
${changesTable}

### Detalji verifikacije

${extractedDetails}

### Provjereni izvori
${sourcesList}

### Izmijenjene datoteke
- \`src/lib/fiscal-data/data/*.ts\`

---
🤖 Generirano automatski pomoću Fiscal Data Validatora

**Napomena:** Pregledajte promjene prije spajanja. Validator koristi AI za ekstrakciju podataka i može imati pogreške.
`
}

/**
 * Update the constants file with new values
 */
async function updateConstantsFile(dataPoint: string, newValue: number | string): Promise<void> {
  // Parse the data point path
  const parts = dataPoint.split(".")
  const root = parts[0] // e.g., 'CONTRIBUTIONS'

  // Map root to file
  const fileMap: Record<string, string> = {
    CONTRIBUTIONS: "contributions.ts",
    TAX_RATES: "tax-rates.ts",
    THRESHOLDS: "thresholds.ts",
    DEADLINES: "deadlines.ts",
    PAYMENT_DETAILS: "payment-details.ts",
    CHAMBER_FEES: "chamber-fees.ts",
    HGK_FEES: "chamber-fees.ts",
  }

  const fileName = fileMap[root]
  if (!fileName) {
    console.warn(`[create-pr] Unknown root: ${root}`)
    return
  }

  const filePath = path.join(process.cwd(), "src/lib/fiscal-data/data", fileName)

  try {
    let content = await readFile(filePath, "utf-8")

    // Simple approach: update lastVerified date
    const today = new Date().toISOString().split("T")[0]
    content = content.replace(/lastVerified:\s*['"][\d-]+['"]/g, `lastVerified: '${today}'`)

    // TODO: More sophisticated value replacement
    // For now, log what needs to be changed manually
    console.log(`[create-pr] Need to update ${dataPoint} to ${newValue} in ${fileName}`)

    await writeFile(filePath, content)
  } catch (error) {
    console.error(`[create-pr] Failed to update ${filePath}:`, error)
  }
}

/**
 * Create a GitHub PR with the changes
 */
export async function createUpdatePR(changes: ValidationResult[]): Promise<string | null> {
  if (changes.length === 0) {
    console.log("[create-pr] No changes to commit")
    return null
  }

  if (!GITHUB_TOKEN) {
    console.error("[create-pr] GITHUB_TOKEN not set")
    return null
  }

  const timestamp = Date.now()
  const branchName = `fiscal-update-${timestamp}`
  const today = new Date().toLocaleDateString("hr-HR")

  try {
    // 1. Create a new branch
    console.log(`[create-pr] Creating branch ${branchName}`)
    await execAsync(`git checkout -b ${branchName}`)

    // 2. Update the constants files
    for (const change of changes) {
      if (change.foundValue !== null) {
        await updateConstantsFile(change.dataPoint, change.foundValue)
      }
    }

    // 3. Update lastVerified dates
    const dataDir = path.join(process.cwd(), "src/lib/fiscal-data/data")
    const todayISO = new Date().toISOString().split("T")[0]

    // 4. Commit changes
    await execAsync("git add src/lib/fiscal-data/")
    await execAsync(`git commit -m "chore(fiscal): update values from official sources

Updated ${changes.length} fiscal value(s) based on weekly validation.

Changes:
${changes.map((c) => `- ${c.dataPoint}: ${c.currentValue} → ${c.foundValue}`).join("\n")}

🤖 Generated by Fiscal Data Validator"`)

    // 5. Push branch
    await execAsync(`git push origin ${branchName}`)

    // 6. Create PR via GitHub API
    const prBody = generatePRBody(changes)

    const response = await fetch(`${GITHUB_API}/repos/${GITHUB_REPO}/pulls`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        title: `🔄 Ažuriranje fiskalnih podataka - ${today}`,
        body: prBody,
        head: branchName,
        base: "main",
      }),
    })

    if (!response.ok) {
      const error = await response.text()
      throw new Error(`GitHub API error: ${error}`)
    }

    const pr = await response.json()
    console.log(`[create-pr] PR created: ${pr.html_url}`)

    // 7. Switch back to main
    await execAsync("git checkout main")

    return pr.html_url
  } catch (error) {
    console.error("[create-pr] Failed to create PR:", error)

    // Try to switch back to main
    try {
      await execAsync("git checkout main")
    } catch {
      // Ignore
    }

    return null
  }
}

/**
 * Create a GitHub issue instead of PR (for manual review)
 */
export async function createValidationIssue(
  changes: ValidationResult[],
  summary: { total: number; matches: number; mismatches: number; errors: number }
): Promise<string | null> {
  if (!GITHUB_TOKEN) {
    console.error("[create-pr] GITHUB_TOKEN not set")
    return null
  }

  const today = new Date().toLocaleDateString("hr-HR")

  const body = `## 📊 Tjedni izvještaj validacije fiskalnih podataka - ${today}

### Sažetak
- ✅ Podudaranja: ${summary.matches}
- ⚠️ Nepodudaranja: ${summary.mismatches}
- ❌ Greške: ${summary.errors}
- 📊 Ukupno provjereno: ${summary.total}

### Otkrivene promjene

${
  changes.length > 0
    ? changes
        .map(
          (c) => `
#### \`${c.dataPoint}\`
- **Trenutna vrijednost:** ${c.currentValue}
- **Pronađena vrijednost:** ${c.foundValue}
- **Pouzdanost:** ${Math.round(c.confidence * 100)}%
- **Izvor:** ${c.sourceUrl}
- **Kontekst:** ${c.extractedText || "N/A"}
`
        )
        .join("\n")
    : "Nisu pronađene promjene."
}

---
🤖 Generirano automatski pomoću Fiscal Data Validatora
`

  try {
    const response = await fetch(`${GITHUB_API}/repos/${GITHUB_REPO}/issues`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${GITHUB_TOKEN}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        title: `📊 Validacija fiskalnih podataka - ${today}`,
        body,
        labels: ["fiscal-data", "automated"],
      }),
    })

    if (!response.ok) {
      const error = await response.text()
      throw new Error(`GitHub API error: ${error}`)
    }

    const issue = await response.json()
    console.log(`[create-pr] Issue created: ${issue.html_url}`)

    return issue.html_url
  } catch (error) {
    console.error("[create-pr] Failed to create issue:", error)
    return null
  }
}
